Protov4/Controllers/AdministradorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Protov4.DAO;
using Protov4.DTO;
using System.Security.Cryptography;

namespace Protov4.Controllers
{
    [Authorize(Policy = "AdminOnly")]
    public class AdministradorController : Controller
    {
        private readonly MikuTechFactory db;
        public AdministradorController(IConfiguration configuration)
        {
            db = new MikutechDAO(configuration);

        }
        public IActionResult Administrador(string tipo, string busqueda)
        {
            try
            {

            var productos = ListarProductos(tipo,busqueda);
            return View("Productos", productos);

            }
            catch (Exception)
            {

                return View("Error");
            }
        }
        [HttpGet]
        public List<ProductoDTO> ListarProductos(string tipo,string busqueda)
        {
            if (busqueda == null)
            {
                busqueda = "Tipo";
            }
            List<ProductoDTO> productos;
            productos = db.GetAllProductos(tipo,busqueda);
            var ProductoDTO = productos.Select(p => new ProductoDTO
            {
                Id = p.Id,
                Nombre_Producto = p.Nombre_Producto,
                Precio = p.Precio,
                Imagen = p.Imagen,
                Marca = p.Marca,
                Existencia = p.Existencia,
                Tipo = p.Tipo,
                Especificaciones = new EspecificacionesDTO
                {
                    Fabricante=p.Especificaciones.Fabricante,
                    Modelo=p.Especificaciones.Modelo,
                    Zócalo=p.Especificaciones.Zócalo,
                    Velocidad=p.Especificaciones.Velocidad,
                    TamañoVRAM=p.Especificaciones.TamañoVRAM,
                    Interfaz=p.Especificaciones.Interfaz,
                    TecnologíaRAM=p.Especificaciones.TecnologíaRAM,
                    Almacenamiento=p.Especificaciones.Almacenamiento,
                    Tamañomemoria=p.Especificaciones.Tamañomemoria,
                    Descripción=p.Especificaciones.Descripción
                }
            }).ToList();

            return ProductoDTO;
        }
        public ActionResult Auditoria()
        {
            try
            {

            var audotira = obtenerAuditoria();
            return View(audotira);

            }
            catch (Exception)
            {

                return View("Error");
            }
        }
        [HttpGet]
        public ActionResult Dashboard()
        {
            try
            {

            
            var dash = db.MasVendidos();
            var prod = db.GetAllProductos(null,"Tipo");
            var combinedData = (MasVendidos: dash, Productos: prod);

            return View(combinedData);
            }
            catch (Exception)
            {

                return View("Error");
            }
        }
        [HttpGet]
        public List<AuditoriaDTO> obtenerAuditoria()
        {
            List<AuditoriaDTO> auditoria;
            auditoria = db.ObtenerAuditoria();
            var AuditoriaDTO = auditoria.Select(p => new AuditoriaDTO
            {
                id_auditoria = p.id_auditoria,
                id_usuario = p.id_usuario,
                nombre_cliente = p.nombre_cliente,
                apellido_cliente = p.apellido_cliente,
                correo_elec = p.correo_elec,
                fecha_inicio_sesion = p.fecha_inicio_sesion,
                fecha_cierre_sesion = p.fecha_cierre_sesion
            }).ToList();

            return AuditoriaDTO;
        }
        public ActionResult CrearNuevoProducto()
        {

            return View();
        }
        [HttpPost]
        public ActionResult NuevoProducto(string nombre, string imagenBase64, float precio, string Marca, int existencia, string tipo, string fabricante, string modelo, string velocidad, string Zócalo, string TamañoVRAM, string Interfaz, string TecnologiaRAM, string tamañomemoria, string Almacenamiento, List<string> Descripcion)
        {
            try
            {

          
            List<string> descripcionList = new List<string>();

            if (Descripcion[0]!=null)
            {
            foreach (string item in Descripcion)
            {
                string[] values = item.Split(',');
                descripcionList.AddRange(values);
            }
            }
            db.InsertarProducto(nombre, imagenBase64, precio, Marca, existencia, tipo, fabricante, modelo, velocidad, Zócalo, TamañoVRAM, Interfaz, TecnologiaRAM, tamañomemoria, Almacenamiento, descripcionList);
            var productos = ListarProductos(null,null);
            return View("Productos", productos);
            }
            catch (Exception)
            {
                return View("Error");

            }
        }
        [HttpPost]
        public ActionResult eliminarProducto(string id)
        {
            try { 
            db.eliminarProducto(id);
            var productos = ListarProductos(null,null);
            return View("Productos", productos);
            }
            catch (Exception)
            {
                return View("Error");

            }
        }
      
        public ActionResult EditarProducto(string _id)
        {
            try { 
            var productos = ObjetoSeleccion(_id);
            return View(productos);
            }
            catch (Exception)
            {
                return View("Error");

            }
        }
        public ActionResult EditarProductoDAO(string _id, string nombre, double precio, string tipo, string imagenBase64, string Marca, int existencia, string Fabricante, string Modelo, string Velocidad, string Zocalo, string TamañoVram, string Interfaz, string NuevasDescripcionesJson, string Tamañomemoria, string TecnologiaRam, string Almacenamiento, List<string> Descripcion)
        {
            List<string> nuevasDescripciones = JsonConvert.DeserializeObject<List<string>>(NuevasDescripcionesJson);
            List<string> descripcionList = new List<string>();

            if (nuevasDescripciones[0] != null)
            {
                foreach (string item in nuevasDescripciones)
                {
                    string[] values = item.Split(',');
                    descripcionList.AddRange(values);
                }
            }
            List<string> descripcionesSinDuplicados = descripcionList.Distinct().ToList();

            db.ActualizarProducto(_id, nombre, precio, tipo, imagenBase64, Marca, existencia, Fabricante, Modelo, Velocidad, Zocalo, TamañoVram, Interfaz, Tamañomemoria, TecnologiaRam, Almacenamiento, descripcionesSinDuplicados);
            var productos = ListarProductos(null,null);
            return View("Productos", productos);
        }
        [HttpGet]
        public List<ProductoDTO> ObjetoSeleccion(string _id)
        {
            List<ProductoDTO> productos;
            productos = db.GetSeleccion(_id);
            var ProductoDTO = productos.Select(p => new ProductoDTO
            {
                Id = p.Id,
                Nombre_Producto = p.Nombre_Producto,
                Precio = p.Precio,
                Imagen = p.Imagen,
                Marca = p.Marca,
                Existencia = p.Existencia,
                Tipo = p.Tipo,
                Especificaciones = new EspecificacionesDTO
                {
                    Fabricante = p.Especificaciones.Fabricante,
                    Modelo = p.Especificaciones.Modelo,
                    Velocidad = p.Especificaciones.Velocidad,
                    Zócalo = p.Especificaciones.Zócalo,
                    TamañoVRAM = p.Especificaciones.TamañoVRAM,
                    Interfaz = p.Especificaciones.Interfaz,
                    Tamañomemoria = p.Especificaciones.Tamañomemoria,
                    TecnologíaRAM = p.Especificaciones.TecnologíaRAM,
                    Almacenamiento = p.Especificaciones.Almacenamiento,
                    Descripción = p.Especificaciones.Descripción
                }

            }).ToList();

            return ProductoDTO;
        }

        public ActionResult Pedidos()
        {
            var pedidos = verPedidos();
            return View(pedidos);
        }
        [HttpGet]
        public List<PedidosDTO> verPedidos()
        {
            List<PedidosDTO> pedidos;
            pedidos = db.VerPedidos();
            var PedidosDTO = pedidos.Select(p => new PedidosDTO
            {
                id_pedido = p.id_pedido,
                ciudad_envio = p.ciudad_envio,
                Calle_principal = p.Calle_principal,
                Calle_secundaria = p.Calle_secundaria,
                nombre_estado = p.nombre_estado
            }).ToList();

            return PedidosDTO;
        }

        [HttpPost]
        public ActionResult CambiarEstado(int id_pedido, int id_tipo_estado)
        {

            db.CambiarEstado(id_pedido, id_tipo_estado);
            var pd = verPedidos();

            return View("Pedidos", pd);

        }
    }
}

Protov4/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Protov4.DAO;
using Protov4.DTO;
using Protov4.Models;
using System.Security.Claims;

namespace Protov4.Controllers
{
    [Authorize]

    public class ProductoController : Controller
    {
        private readonly MikuTechFactory db;
        private static bool pedido = false;


        public ProductoController(IConfiguration configuration)
        {
            db = new MikutechDAO(configuration);
           
        }

        // GET: ProductoController/Producto
        // Muestra una lista de productos filtrados por tipo
        public ActionResult Producto(string tipo,string busqueda)
        {
            try
            {

            
            var productos = ListarProductos(tipo,busqueda);
            if (busqueda== "Nombre_Producto" || busqueda=="Marca")
            {
                ViewData["tipo"] = "Resultados de: "+tipo;
            }
            else { 
            ViewData["tipo"] = tipo;
            }
            return View(productos);

            }
            catch (Exception)
            {

                return View("Error");
            }
        }
     
        // GET: ProductoController/ProductoSeleccion
        // Muestra los detalles de un producto específico seleccionado por ID
        public ActionResult ProductoSeleccion(string _id)
        {
            try
            {

            
            var productos = ObjetoSeleccion(_id);
            return View(productos);
            }
            catch (Exception)
            {

                return View("Error");
            }
        }
        // Método auxiliar HTTP GET: Obtiene los detalles de un producto seleccionado por ID
        [HttpGet]
        public List<ProductoDTO> ObjetoSeleccion(string _id)
        {
            List<ProductoDTO> productos;
            productos = db.GetSeleccion(_id);
            var ProductoDTO = productos.Select(p => new ProductoDTO
            {
                Id = p.Id,
                Nombre_Producto = p.Nombre_Producto,
                Precio = p.Precio,
                Imagen = p.Imagen,
                Marca = p.Marca,
                Existencia = p.Existencia,
                Tipo = p.Tipo,
                Especificaciones = new EspecificacionesDTO
                {
                    Fabricante = p.Especificaciones.Fabricante,
                    Modelo = p.Especificaciones.Modelo,
                    Velocidad = p.Especificaciones.Velocidad,
                    Zócalo = p.Especificaciones.Zócalo,
                    TamañoVRAM = p.Especificaciones.TamañoVRAM,
                    Interfaz = p.Especificaciones.Interfaz,
                    Tamañomemoria = p.Especificaciones.Tamañomemoria,
                    TecnologíaRAM = p.Especificaciones.TecnologíaRAM,
                    Almacenamiento = p.Especificaciones.Almacenamiento,
                    Descripción = p.Especificaciones.Descripción
                }
               
            }).ToList();

            return ProductoDTO;
        }
        // Método auxiliar HTTP GET: Obtiene una lista de productos filtrados por tipo
        [HttpGet]
        public List<ProductoDTO> ListarProductos(string tipo,string Busqueda)
        {
            if (Busqueda==null)
            {
                Busqueda = "Tipo";
            }
            List<ProductoDTO> productos;
            productos = db.GetAllProductos(tipo,Busqueda);
            var ProductoDTO = productos.Select(p => new ProductoDTO
            {
                Id = p.Id,
                Nombre_Producto = p.Nombre_Producto,
                Precio = p.Precio,
                Imagen = p.Imagen,
                Marca = p.Marca,
                Existencia = p.Existencia,
                Tipo = p.Tipo
            }).ToList();

            return ProductoDTO;
        }

        // GET: ProductoController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductoController/Create
        public ActionResult Create()
        {
            return View();
        }
        // POST: ProductoController/CrearCarrito
        // Agrega un producto al carrito de compras
        [HttpPost]
        public ActionResult CrearCarrito(int id_cliente, string id_producto, decimal precio, int cantidad, decimal subtotal)
        {
            try
            {
                int id_pedido;
               
                if (HttpContext.Session.GetInt32("IdPedidoActual") != null)
                {
                   
                    id_pedido = db.ObtenerIdPedido();

                    TempData["PedidoRegistrado"] = true;
                    HttpContext.Session.SetInt32("IdPedidoActual", id_pedido);
                }
                else
                {
                    ClaimsPrincipal cl = HttpContext.User;
                    if (cl.Identity != null && cl.Identity.IsAuthenticated) // Verificar si el usuario está autenticado y obtener su ID de cliente para listar sus pedidos
                    {
                        if (int.TryParse(cl.FindFirstValue("id_cliente"), out int idCliente))
                        {
                            db.RegistrarPedido(idCliente);
                        }
                    }
                    id_pedido = db.ObtenerIdPedido();
                    TempData["PedidoRegistrado"] = true;
                    HttpContext.Session.SetInt32("IdPedidoActual", id_pedido);
                   
                }
                
                db.insertarCarrito(id_pedido, id_producto, precio, cantidad, subtotal);

                return Json(new { success = true });
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }


        // POST: ProductoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductoController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProductoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductoController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ProductoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Protov4/Views/Administrador/Auditoria.cshtml
@using Protov4.DTO;
@{
    Layout = "~/Views/Administrador/_LayoutAdmin.cshtml";
}
@model List<AuditoriaDTO>
@section styles {
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" />
    <link href="~/css/auditoria.css" rel="stylesheet" asp-append-version="true" />
}
<div class="title-auditoria">
    <h1>Auditoria<i class="fa fa-file-text" style="margin-left: 15px; margin-bottom: 3px; font-size: 28px;"></i></h1>
</div>
<div class="filter-section">
</div>
<div class="container-custom">
    <table id="auditoriaTable" class="tabla-pedidos">
        <thead>
            <tr>
                <th>Id_Auditoria</th>
                <th>Id_Usuario</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Correo electrónico</th>
                <th>Fecha_Inicio_Sesión</th>
                <th>Fecha_Cierre_Sesión</th>
            </tr>
        </thead>

        @for (int i = 0; i < Model.Count; i++)
        {
            var carr = Model[i];

            <tr>
                <td> @carr.id_auditoria</td>
                <td> @carr.id_usuario</td>
                <td> @carr.nombre_cliente</td>
                <td> @carr.apellido_cliente</td>
                <td> @carr.correo_elec</td>
                <td> @carr.fecha_inicio_sesion</td>
                <td>@carr.fecha_cierre_sesion </td>
            </tr>
        }
    </table>
</div>

@section scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function () {
            const dataTable = $('#auditoriaTable').DataTable({
                paging: true, // Habilita la paginación
                pageLength: 10, // Número de filas por página
                lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]], // Opciones de número de filas por página
                language: {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }
                }
                });

            $('#search-button').click(function () {
                dataTable.search($('#search').val()).draw();
            });

            $('#date-filter-button').click(function () {
                const startDate = $('#startDate').val();
                const endDate = $('#endDate').val();
                dataTable.columns(5).search(startDate, endDate).draw();
            });
        });
    </script>
}

Protov4/Views/Administrador/Dashboard.cshtml
@using Protov4.DTO
@{
    Layout = "~/Views/Administrador/_LayoutAdmin.cshtml";
}
@model (List<DashboardDTO> dash,List<ProductoDTO> prod)
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

<div class="m-2">
    <h1>Dashboard</h1>
    <div class="row">
        <div class="col-xl-3 col-md-6">
            <div class="card bg-primary text-white mb-4">
                <div class="card-body"> <i class="fa-solid fa-tags fa-fade"></i> Se han realizado un total de @Model.dash.Count Ventas</div>
                <div class="card-footer d-flex align-items-center justify-content-between">
                    <a class="small text-white stretched-link" href="@Url.Action("Pedidos", "Administrador")">Ver Detalles</a>
                    <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                </div>
            </div>
        </div>
        @{
            int cantidad = 0;
            foreach (var item in Model.prod)
            {
                if (item.Existencia < 10 && item.Existencia != 0)
                {
                    cantidad++;
                }
            }
            <div class="col-xl-3 col-md-6">
                <div class="card bg-warning text-white mb-4" data-toggle="modal" data-target="#lowInventoryModal">
                    <div class="card-body"><i class="fa-solid fa-circle-exclamation fa-fade"></i> Tienes @cantidad Productos con poca existencia</div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small text-white stretched-link" href="#" data-toggle="modal" data-target="#lowInventoryModal">Ver Detalles</a>
                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>


        }
        @{
            int cantidadprod = 0;
            foreach (var item in Model.dash)
            {
                cantidadprod = item.cantidad + cantidadprod;
            }
            <div class="col-xl-3 col-md-6">
                <div class="card bg-success text-white mb-4">
                    <div class="card-body"><i class="fa-solid fa-clipboard-check fa-fade"></i> Se han vendido @cantidadprod Productos en total</div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small text-white stretched-link"></a>
                        <div class="small text-white"><i class="fa-solid fa-minus" style="color: #198754;"></i></div>
                    </div>
                </div>
            </div>
        }
        @{
            int cantidadnulos = 0;
            foreach (var item in Model.prod)
            {
                if (item.Existencia == 0 )
                {
                    cantidadnulos++;
                }
            }
            <div class="col-xl-3 col-md-6">
                <div class="card bg-danger text-white mb-4 " data-toggle="modal" data-target="#zeroInventoryModal">
                    <div class="card-body"><i class="fa-solid fa-triangle-exclamation fa-shake"></i> Tienes @cantidadnulos Productos con 0 existencias</div>
                    <div class="card-footer d-flex align-items-center justify-content-between">
                        <a class="small text-white stretched-link" href="#" data-toggle="modal" data-target="#zeroInventoryModal">Ver Detalles</a>
                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                    </div>
                </div>
            </div>
        }
        <div class="col-xl-6">
            <div class="card mb-4">
                <div class="card-header">
                    <i class="fa-solid fa-chart-column"></i>
                    TOP 10 Productos más Vendidos
                </div>
                <div class="card-body"><canvas id="myBarChart" width="100%" height="60px"></canvas></div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="card mb-4 ">
                <div class="card-header">
                    <i class="fas fa-chart-pie me-1"></i>
                    Top Categorias más vendidas
                </div>
                <div class="card-body"><canvas id="myPieChart" style="max-width: 100%; max-height: 360px;"></canvas></div>
            </div>
        </div>
    </div>

</div>
<div class="modal fade" id="lowInventoryModal" tabindex="-1" role="dialog" aria-labelledby="lowInventoryModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="lowInventoryModalLabel">Productos con poca existencia</h5>
                <button type="button" class="close closeModalButton" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <ul id="lowInventoryList" class="list-group">
                    <!-- Product items will be added here -->
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary closeModalButton" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="zeroInventoryModal" tabindex="-1" role="dialog" aria-labelledby="zeroInventoryModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="zeroInventoryModalLabel">Productos sin existencia</h5>
                <button type="button" class="close closeModalButton" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <ul id="zeroInventoryList" class="list-group">
                    <!-- Product items without inventory will be added here -->
                </ul>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary closeModalZeroButton" data-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>
<!-- Asegurarse de que jQuery y Bootstrap estén incluidos antes de tu script -->
<script src="ruta/a/jquery.min.js"></script>
<script src="ruta/a/bootstrap.min.js"></script>

<script>
    $(document).ready(function () {
        $('#lowInventoryModal').on('show.bs.modal', function () {
            var lowInventoryList = $('#lowInventoryList');
            lowInventoryList.empty(); // Clear previous content

            // Iterate through products with low inventory and add them to the modal
    @foreach (var item in Model.prod)
    {
        if (item.Existencia < 10 && item.Existencia != 0)
        {
            <text>lowInventoryList.append('<li class="list-group-item">@item.Nombre_Producto Tiene @item.Existencia existencias</li>'); </text>
        }
    }
                });
        $('.card[data-toggle="modal"]').click(function () {
            var targetModal = $(this).data('target');
            $(targetModal).modal('show');
        });
        $('.closeModalButton').click(function () {
            $('#lowInventoryModal').modal('hide');
        });
        $('#zeroInventoryModal').on('show.bs.modal', function () {
            var zeroInventoryList = $('#zeroInventoryList');
            zeroInventoryList.empty(); // Clear previous content

            // Iterate through products with zero inventory and add them to the modal
    @foreach (var item in Model.prod)
    {
        if (item.Existencia == 0)
        {
            <text>zeroInventoryList.append('<li class="list-group-item">@item.Nombre_Producto</li>'); </text>
        }
    }
    });
        $('.card[data-toggle="modal"]').click(function () {
            var targetModal = $(this).data('target');
            $(targetModal).modal('show');
        });
        $('.closeModalZeroButton').click(function () {
            $('#zeroInventoryModal').modal('hide');
        });
        var ctx = document.getElementById('myBarChart').getContext('2d');

        var originalLabels = @Html.Raw(Json.Serialize(Model.dash.Select(p => p.Nombre_Producto)));
        var originalData = @Html.Raw(Json.Serialize(Model.dash.Select(p => p.cantidad)));

        var limitedLabels = originalLabels.slice(0, 10);
        var limitedData = originalData.slice(0, 10);

        var data = {
            labels: limitedLabels,
            datasets: [{
                label: 'Cantidad Vendida',
                data: limitedData,
                backgroundColor: 'rgba(2,117,216,1)',
                borderColor: 'rgba(2,117,216,1)',
            }]
        };
        var options = {
            tooltips: {
                callbacks: {
                    title: function (tooltipItem, data) {
                        return originalLabels[tooltipItem[0].index];
                    },
                    label: function (tooltipItem, data) {
                        return 'Cantidad Vendida: ' + tooltipItem.formattedValue;
                    }
                }
            },
            scales: {
                x: {
                    ticks: {
                        autoSkip: false,
                        maxRotation: 35,
                        minRotation: 35,
                        maxTicksLimit: 5,

                        callback: function (value, index, values) {
                            const maxLength = 15;
                            return originalLabels[value].length > maxLength ? originalLabels[value].substring(0, maxLength) + '...' : originalLabels[value];
                        }
                    }
                },
                y: {
                    beginAtZero: true
                }
            }
        };

        var myBarChart = new Chart(ctx, {
            type: 'bar',
            data: data,
            options: options
        });

        var pieCtx = document.getElementById('myPieChart').getContext('2d');

        var pieLabels = @Html.Raw(Json.Serialize(Model.dash.Select(p => p.tipo)));
        var pieData = @Html.Raw(Json.Serialize(Model.dash.Select(p => p.cantidad)));

        var pieColors = generateCustomColors(pieLabels.length);

        var pieChartData = {
            labels: pieLabels,
            datasets: [{
                data: pieData,
                backgroundColor: pieColors
            }]
        };

        var pieChartOptions = {
            responsive: true
        };

        var myPieChart = new Chart(pieCtx, {
            type: 'pie',
            data: pieChartData,
            options: pieChartOptions
        });

        function generateCustomColors(count) {
            var predefinedColors = ['#5148f2', '#548de9', '#aa49ee', '#f39632', '#d3433d', '#b43a42', '#d53f69', '#5ac1b4', '#23587a', '#7a8b9f'];
            var colors = [];

            for (var i = 0; i < count; i++) {
                var colorIndex = i % predefinedColors.length;
                colors.push(predefinedColors[colorIndex]);
            }

            return colors;
        }
    });
</script>